### ISSUE TITLE
It seems you are not using emoji for your git commits 😅

### ISSUE THREAD

**Issue by clenemt** [dakl/dotfiles#1]
I heard through the grapevines that you were an emoji fan, so here you go https://gitmoji.dev/

**Comment by clenemt** [comment]
Any news on that @dakl ?

**Comment by dakl** [comment]
Yes finally!! I added some key mappings so now I'm gonna use emoji like crazy!!

**Comment by dakl** [comment]
https://github.com/dakl/dotfiles/commit/7f284fc0917f7eebc83ecbb097a0b351e553a8f3

**Comment by clenemt** [comment]
Finally I can use this repo, thank you!
